workflows:
  ios-workflow:
    name: iOS Workflow - TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    working_directory: weblser_app
    environment:
      flutter: 3.35.6
      groups:
        - ios_credentials
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "io.jumoki.weblser"
        APP_ID_NAME: "weblser - AI Website Analyzer"
        APPLE_DEVELOPER_TEAM_ID: $APPLE_DEVELOPER_TEAM_ID
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Fetch iOS code signing files from Apple Developer Portal
        script: |
          app-store-connect fetch-signing-files io.jumoki.weblser \
            --create \
            --type IOS_APP_STORE \
            --platform IOS \
            --issuer-id $APPLE_API_KEY_ISSUER_ID \
            --key-id $APPLE_API_KEY_ID \
            --private-key @env:AUTH_KEY \
            --certificate-key @env:CERTIFICATE_KEY
      - name: Build iOS App
        script: flutter build ios --release --no-codesign -t lib/main.dart
      - name: Build and archive
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -derivedDataPath build/ios_build \
            -archivePath build/ios_build/Runner.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE="Automatic" \
            DEVELOPMENT_TEAM="$APPLE_DEVELOPER_TEAM_ID" \
            archive
      - name: Export IPA
        script: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/ios_build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios_build/ipa \
            -allowProvisioningUpdates
    artifacts:
      - build/ios_build/ipa/*.ipa
      - build/ios_build/Runner.xcarchive
    publishing:
      app_store_connect:
        api_key: $APPLE_API_KEY
        key_id: $APPLE_API_KEY_ID
        issuer_id: $APPLE_API_KEY_ISSUER_ID
        submit_to_testflight: true

  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux
    working_directory: weblser_app
    environment:
      flutter: 3.35.6
      android_signing:
        - keystore_reference
      groups:
        - android_credentials
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build AppBundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $ANDROID_KEYSTORE_CREDENTIALS
        track: internal
