workflows:
  ios-workflow:
    name: iOS Workflow - TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.35.6
      groups:
        - ios-signing
      vars:
        XCODE_WORKSPACE: "weblser_app/ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "io.jumoki.weblser"
        APP_ID_NAME: "weblser - AI Website Analyzer"
        APPLE_DEVELOPER_TEAM_ID: PKB9P8F266
    scripts:
      - name: Debug environment
        script: |
          pwd
          ls -la
          flutter --version
          dart --version
      - name: Get Flutter packages
        script: |
          cd weblser_app
          pwd
          ls -la pubspec.yaml
          flutter pub get -v
      - name: Clean Flutter build cache
        script: |
          cd weblser_app
          flutter clean
      - name: Decode certificate and setup signing
        script: |
          echo $CERT_KEY | base64 --decode > ~/ios_certificate.p12
          app-store-connect fetch-signing-files io.jumoki.weblser \
            --create \
            --type IOS_APP_STORE \
            --platform IOS \
            --issuer-id $ISSUER_ID \
            --key-id $KEY_ID \
            --private-key @env:AUTH_KEY \
            --certificate-key ~/ios_certificate.p12 \
            --p12-password ""
      - name: Build iOS App
        script: |
          cd weblser_app
          flutter build ios --release --no-codesign -t lib/main.dart
      - name: Build and archive
        script: |
          cd weblser_app/ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -derivedDataPath build/ios_build \
            -archivePath build/ios_build/Runner.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE="Automatic" \
            DEVELOPMENT_TEAM="$APPLE_DEVELOPER_TEAM_ID" \
            archive
      - name: Export IPA
        script: |
          cd weblser_app/ios
          xcodebuild -exportArchive \
            -archivePath build/ios_build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios_build/ipa \
            -allowProvisioningUpdates
    artifacts:
      - weblser_app/build/ios_build/ipa/*.ipa
      - weblser_app/build/ios_build/Runner.xcarchive
    publishing:
      app_store_connect:
        api_key: $AUTH_KEY
        key_id: $KEY_ID
        issuer_id: $ISSUER_ID
        submit_to_testflight: true

  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux
    environment:
      flutter: 3.35.6
      android_signing:
        - keystore_reference
    scripts:
      - name: Get Flutter packages
        script: |
          cd weblser_app
          flutter pub get -v
      - name: Build APK
        script: |
          cd weblser_app
          flutter build apk --release
      - name: Build AppBundle
        script: |
          cd weblser_app
          flutter build appbundle --release
    artifacts:
      - weblser_app/build/app/outputs/flutter-apk/*.apk
      - weblser_app/build/app/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $ANDROID_KEYSTORE_CREDENTIALS
        track: internal
